version: '3.7'
services:
  vk-backend:
    image: url/vk-backend:latest
    container_name: vk-container
    ports:
      - "80:1337"
    environment:
      - NODE_ENV=production
    restart: always
  gifnot:
    image: url/vkgifnot:latest
    container_name: gifnot-container
    environment:
      - GIF_TOKEN=enter_token
      - NOTIFIER_TOKEN=enter_token
      - NOTIFIED_USERS=enter_user_ids
    restart: always
  telegram-book-bot:
    image: url/telegram-book-bot:latest
    container_name: book-bot
    ports:
      - "1402:1402"
    restart: always
  memcached:
    image: memcached:1.6.9
    container_name: memcached
    ports:
      - "11211:11211"
    restart: always