version: '3.7'
services:
  vk-backend:
    image: jagmesh/vk-backend:latest
    container_name: vk-container
    ports:
      - "80:1337"  
    restart: always
  gifnot:
    image: garageorder/vkgifnot:latest
    container_name: gifnot-container
    environment:
      - GIF_TOKEN=enter_token
      - NOTIFIER_TOKEN=enter_token
      - NOTIFIED_USERS=enter_user_ids
    restart: always
  telegram-book-bot:
    image: cr.selcloud.ru/jagmesh-vm/telegram-book-bot:latest
    container_name: book-bot
    ports:
      - "1402:1402"
    restart: always